export default {
  // User
  USER_SIGN_IN: 'USER_SIGN_IN',
  USER_SIGN_OUT: 'USER_SIGN_OUT',
  // Employee
  EMPLOYEES_SET: 'EMPLOYEES_SET',
  EMPLOYEE_ADD: 'EMPLOYEE_ADD',
  EMPLOYEE_CREATE: 'EMPLOYEE_CREATE',
  EMPLOYEE_REMOVE: 'EMPLOYEE_REMOVE',
  EMPLOYEE_UPDATE: 'EMPLOYEE_UPDATE',
}